blueprints/root.py
from flask import Blueprint, redirect, render_template, url_for
from classes.component import ComponentContainer
from classes.tool import ToolContainer

def Root(CC:ComponentContainer, TC:ToolContainer) -> Blueprint:

    bp = Blueprint('root', __name__, url_prefix='/')

    @bp.route('/')
    def index():
        return render_template('index.html')

    @bp.route('/home')
    def home():
        return render_template('Home.html')

    @bp.route('/under-construction')
    def under_construction():
        return render_template('under-construction.html')

    @bp.route('/favicon.ico')
    def favicon():
        return redirect(url_for('static',filename='favicon.ico'))

    return bp

templates/base/Base.html
<!DOCTYPE html>
<html lang="{{ PageSetting.language }}" dir="{{ PageSetting.dir }}"> 
  <head>
    <meta charset="{{ PageSetting.charset }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ PageSetting.pagetitle }}</title>
    <!---->
      {% if PageSetting.language == 'fa' %}
        {% if PageSetting.fontvazirmtn %}
          <link rel="stylesheet" href="{{url_for('static', filename='vazirmatn/Vazirmatn-font-face.css')}}">
          <link rel="stylesheet" href="{{url_for('static', filename='vazirmatn/Vazirmatn-Variable-font-face.css')}}">
        {% endif %}
        {% if PageSetting.bootstrap %}<link rel="stylesheet" href="{{url_for('static', filename='bootstrap/bootstrap.rtl.min.css')}}">{% endif %}
      {% elif PageSetting.language == 'en' %}
        {% if PageSetting.bootstrap %}<link rel="stylesheet" href="{{url_for('static', filename='bootstrap/bootstrap.min.css')}}">{% endif %}
      {% endif %}
      {% if PageSetting.main %}<link rel="stylesheet" href="{{url_for('static', filename='main.css')}}">{% endif %}
      {% if PageSetting.fontawesome %}<link rel="stylesheet" href="{{url_for('static', filename='fontawesome/css/all.min.css')}}">{% endif %}
      <!-- Custom Styles -->
      {% block Style %}{% endblock %}
  </head>
  <body>
    <!-- Imports -->
    {% import 'base/elements/button.html' as Button %}
    {% import 'base/elements/icon.html' as Icon %}

    {% block Sidebar %}{% include 'base/sidebar.html' %}{% endblock %}
    {% block Header %}{% include 'base/header.html' %}{% endblock %}
    {% block Content %}<!-- Content Block -->{% endblock %}
    {% block Footer %}{% include 'base/footer.html' %}{% endblock %}
    <!-- Scripts -->
    {% if PageSetting.bootstrap %}<script src="{{url_for('static', filename='bootstrap/bootstrap.bundle.min.js')}}"></script>{% endif %}
    {% if PageSetting.jquery %}<script src="{{url_for('static', filename='jquery/jquery.min.js')}}"></script>{% endif %}
    {% if PageSetting.main %}<script src="{{url_for('static', filename='main.js')}}"></script>{% endif %}
    {% block Script %}{% endblock %}
  </body>
</html>

templates/base/Footer.html
<footer class="text-center text-lg-start text-dark" style="background-color: #ECEFF1">
  <section class="d-flex justify-content-between p-4 text-white" style="background-color: #4c88e9">
    <div class="me-5"><span>مارا در این پلتفرم ها دنبال کنید :</span></div>
    <div>
      <a href="https://www.instagram.com/radinsystem/" class="text-white me-4 text-decoration-none"><i class="fab fa-facebook-f"></i></a>
      <a href="#" class="text-white me-4 text-decoration-none"><i class="fab fa-twitter"></i></a>
      <a href="#" class="text-white me-4 text-decoration-none"><i class="fab fa-google"></i></a>
      <a href="#" class="text-white me-4 text-decoration-none"><i class="fab fa-instagram"></i></a>
      <a href="#" class="text-white me-4 text-decoration-none"><i class="fab fa-linkedin"></i></a>
      <a href="https://github.com/radin-system" class="text-white me-4 text-decoration-none"><i class="fab fa-github"></i></a>
    </div>
  </section>
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <div class="row mt-3">
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold">رادین سیستم</h6>
          <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 75px; background-color: #1f23ff; height: 2px"/>
          <p>اراعه دهنده خدمات کامپیوتری در تهران</p>
        </div>
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold">منابع طراحی سایت</h6>
          <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 75px; background-color: #1f23ff; height: 2px"/>
          <p><a href="https://OpenAI.io/" class="text-dark">OpenAI</a></p>
          <p><a href="https://getbootstrap.com/" class="text-dark">MDBootstrap</a></p>
          <p><a href="https://w3schools.com/" class="text-dark">W3School</a></p>
          <p><a href="https://python.org/" class="text-dark">Python3</a></p>
        </div>
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold">میانبر ها</h6>
          <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 75px; background-color: #1f23ff; height: 2px"/>
          <p><a href="https://rsto.ir/%d8%af%d8%b1%d8%a8%d8%a7%d8%b1%d9%87-%d9%85%d8%a7/" class="text-dark text-decoration-none">درباره ما</a></p>
        </div>
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <h6 class="text-uppercase fw-bold">تماس با ما</h6>
            <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px; background-color: #7c4dff; height: 2px"/>
            <p><i class="fas fa-home mr-3"></i>تهران – کیلومتر۱۹ بزرگراه فتح – بلوار تولیدگران – پلاک ۱۶۹ – ساختمان اداری یاس – واحد 6</p>
            <p><i class="fas fa-envelope mr-3"></i> Support@rsto.ir </p>
            <p><i class="fas fa-phone mr-3"></i> 021-45885000 </p>
            <p><i class="fas fa-mobile-alt mr-3"></i> 0905-468-4980 </p>
        </div>
      </div>
    </div>
  </section>
  <div class="text-center p-3" style="background-color: #ECEFF1">
    COPYRIGHT : <a class="text-dark" href="https://rsto.ir/"> RSTO.IR </a>
  </div>
</footer>

templates/base/Header.html
<header class="p-3 mb-3 border-bottom lg-light">
  <div class="container">
    <!-- Header -->
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-4 mb-4 border-bottom">
      <a href="{{url_for('root.index')}}" class="d-flex align-items-center col-md-2 mb-2 mb-md-0 text-dark text-decoration-none"><h5>پنل پشتیبانی</h5></a>
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{url_for('root.index')}}" class="nav-link px-3 link-dark">خانه</a></li>
        {% if Current_User.is_authenticated %}<li><a href="{{url_for('root.under_construction')}}" class="nav-link px-3 link-dark">داشبورد</a></li>{%endif%}
        <li><a href="https://rsto.ir/%d8%ae%d8%af%d9%85%d8%a7%d8%aa-%d8%b4%d8%a8%da%a9%d9%87-%da%a9%d8%a7%d9%85%d9%be%db%8c%d9%88%d8%aa%d8%b1%db%8c/" class="nav-link px-3 link-dark">خدمات شبکه</a></li>
        <li><a href="https://rsto.ir/%d9%85%d9%82%d8%a7%d9%84%d8%a7%d8%aa-%d8%b1%d8%a7%d8%af%db%8c%d9%86-%da%a9%d8%a7%d9%84%d8%a7/" class="nav-link px-3 link-dark">مقالات</a></li>
        <li><a href="https://radin-system.com/" class="nav-link px-3 link-dark">فروشگاه</a></li>
        <li><a href="https://rsto.ir/%d8%af%d8%b1%d8%a8%d8%a7%d8%b1%d9%87-%d9%85%d8%a7/" class="nav-link px-3 link-dark">درباره ما</a></li>
      </ul>
      {% if Current_User.is_authenticated %}
        {% with User=Current_User , Dropdown=True %}
          {% include 'base/widget/usersmall.html' %}
        {% endwith %}
      {% else %}
        <div class="col-md-3 text-end">
          {% include 'base/modal/login.html' %}
        </div>
      {% endif %}
    </header>
    <!-- Breadcrump -->
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-chevron p-1 bg-body-tertiary rounded-3">
          <li class="breadcrumb-item"><a class="link-body-emphasis" href="{{url_for('root.index')}}"><i class="fas fa-home"><span class="visually-hidden">Home</span></i></a></li>
          <li class="breadcrumb-item"><a class="link-body-emphasis fw-semibold text-decoration-none" href="{{url_for('root.index')}}">اصلی</a></li>
          <li class="breadcrumb-item active" aria-current="page">خانه</li>
        </ol>
      </nav>
    </div>
  </div>
</header>

templates/base/sidebar.html
<button id="darkModeToggle" class="btn btn-primary btn-dark-mode">حالت شب</button>