blueprints/auth.py
from flask import Blueprint, abort, request, render_template, redirect, url_for
from flask_login import logout_user, login_user

from classes.component import ComponentContainer, SQLManager
from classes.policy.input import PasswordPolicy, UsernamePolicy
from classes.tool import ToolContainer

def Auth(CC:ComponentContainer, TC:ToolContainer) -> Blueprint:
    SQL:SQLManager = CC.Get('Main_SQLManager')

    bp = Blueprint('auth', __name__, url_prefix='/auth')

    @bp.route('/')
    def index():
        return redirect(url_for('auth.login'))

    @bp.route('/login' , methods=['GET','POST'])
    def login():
        if request.method == 'GET' : return render_template('auth/login.html')
        if request.method == 'POST':
            # Getting requierd form fields
            Loging_User = request.form.get('username')
            Loging_Pass = request.form.get('password')
            
            # Check for Input policy
            try: 
                Loging_User = UsernamePolicy.Apply(Loging_User)
                Loging_Pass = PasswordPolicy.Apply(Loging_Pass)
            except: 
                return abort(401)

            # Check if filds are proprly inputed
            if Loging_User and Loging_Pass:
                # getting the user
                User = SQL.Query(SQL.User,First=True, username=Loging_User)
                if User:
                    # Comparing password
                    if User.password == Loging_Pass :
                        login_user(User)
                        return redirect(url_for('root.index'))

            return abort(401)

    @bp.route('/logout' , methods=['GET','POST'])
    def logout():
        logout_user()
        return redirect(url_for('root.index'))

    @bp.route('/register' , methods=['GET','POST'])
    def register():
        if   request.method == 'GET'  : return render_template('auth/register.html')
        elif request.method == 'POST' :
            raise NotImplementedError('Route not implemented yet')
    
    return bp

blueprints/root.py
from flask import Blueprint, redirect, render_template, url_for
from classes.component import ComponentContainer
from classes.tool import ToolContainer

def Root(CC:ComponentContainer, TC:ToolContainer) -> Blueprint:

    bp = Blueprint('root', __name__, url_prefix='/')

    @bp.route('/')
    def index():
        return render_template('index.html')

    @bp.route('/home')
    def home():
        return render_template('Home.html')

    @bp.route('/under-construction')
    def under_construction():
        return render_template('under-construction.html')

    @bp.route('/favicon.ico')
    def favicon():
        return redirect(url_for('static',filename='favicon.ico'))

    return bp

templates/base/widget/CompanyCard.html
{% if Company %}
<div class="card bg-light mb-3">
  {% if Header %}
    <div class="card-header text-center"><strong>{{ Header }}</strong></div>
  {% endif %}
  <div class="card-body">
    <div class="d-flex flex-column align-items-center text-center">
      <img src="{{url_for('static',filename=Company.logo)}}" alt="Avatar" class="rounded-circle" height="150" width="150">
      <div class="mt-3">
        <h5 class="mb-2">{{ Company.name_en }}</h5>
        <p class="text-secondary mb-2">{{ Company.name_fa }}</p>
        <p class="text-secondary mb-2">{{ Company.domain }}</p>
      </div>
    </div>
  </div>
  {% if Footer %}
    <div class="card-footer text-center"></div><strong>{{ Footer }}</strong></div>
  {% endif %}
</div>
{% endif %}

templates/base/widget/UserCard.html
{% if User %}
<div class="card bg-light mb-3">
  {% if Header %}
    <div class="card-header text-center"><strong>{{ Header }}</strong></div>
  {% endif %}
  <div class="card-body">
    <div class="d-flex flex-column align-items-center text-center">
      <img src="{{url_for('static',filename=User.avatar_path)}}" alt="Avatar" class="rounded-circle" height="150" width="150">
      <div class="mt-3">
        <h5 class="mb-2">{{ User.fullname_en }}</h5>
        <p class="text-secondary mb-2">{{ User.fullname_fa }}</p>
        <p class="text-secondary mb-2">{{ User.position }}</p>
        <p class="text-muted font-size-sm mb-2">{{ User.username }}</p>
      </div>
    </div>
  </div>
  {% if Footer %}
    <div class="card-footer text-center"></div><strong>{{ Footer }}</strong></div>
  {% endif %}
</div>
{% endif %}

templates/base/widget/UserSmall.html
{% if User %}
  <div class="flex-shrink-0 {% if Dropdown %}dropdown{% endif %}">
    <a href="{% if not Dropdown %}{{url_for('User.Profile',id=User.id)}}{% endif %}" class="d-block link-dark text-decoration-none {% if Dropdown %}dropdown-toggle{% endif %}" id="UserProfile" {% if Dropdown %}data-bs-toggle="dropdown"{% endif %} aria-expanded="false">
      <img src="{{url_for('static',filename=User.avatar_path)}}" alt="Avatar" width="45" height="45" class="rounded-circle"> {{ User.fullname_fa }}
    </a>
    {% if Dropdown %}
      <ul class="dropdown-menu text-small shadow" aria-labelledby="UserDropdown">
        <li class="dropdown-item"> {{ User.fullname_en }}</li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{{url_for('root.under_construction')}}">تیکت ها</a></li>
        <li><a class="dropdown-item" href="{{url_for('user.profile')}}">پروفایل</a></li>
        {%if current_user.admin%}
        <li><a class="dropdown-item" href="{{url_for('root.under_construction')}}">تنظیمات</a></li>
        {%endif%}
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">خروج</a></li>
      </ul>
    {% endif %}
  </div>
{% endif %}